ccflags-y :=                            \
        -Idrivers/misc/sprdwcn_bsp/sc23xx/include \
        -Idrivers/misc/sprdwcn_bsp/sc23xx/platform \
        -Idrivers/misc/sprdwcn_bsp/sc23xx/platform/rf
obj-$(CONFIG_SC2342_INTEG) +=  wcn_integrate_dev.o \
	wcn_integrate_boot.o wcn_integrate.o
