#!/bin/sh

. /lib/functions.sh

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0

	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -lt 1 ]
	then
		if [ -f /etc/rc.button/wps ]
		then
			BUTTON=wps ACTION=pressed /etc/rc.button/wps
		else
			echo "REBOOT" > /dev/console
			sync
			reboot
		fi
	elif [ "$SEEN" -gt 5 -a -n "$OVERLAY" ]
	then
		echo "FACTORY RESET" > /dev/console
		jffs2reset -y && reboot &
	fi
;;
esac

return 0
