#!/bin/sh /etc/rc.common
# Copyright (C) 2016 monokoo <realstones2012@gmail.com>

CONFIG=shadowsocks
LOCK_FILE=/var/lock/onlineconfig.lock

config_t_get() {
	local index=0
	[ -n "$3" ] && index=$3
	local ret=$(uci get $CONFIG.@$1[$index].$2 2>/dev/null)
	#echo ${ret:=$3}
	echo $ret
}

config_t_set() {
	index=$3
	uci set $CONFIG.@$1[$index].$2=$4
}

decode_url_link(){
	link=$1
	num=$2
	len=$((${#link}-$num))
	mod4=$(($len%4))
	if [ "$mod4" -gt 0 ]; then
		var="===="
		newlink=${link}${var:$mod4}
		echo -n "$newlink" | sed 's/-/+/g; s/_/\//g' | /usr/bin/base64 -d -i 2> /dev/null
	else
		echo -n "$link" | sed 's/-/+/g; s/_/\//g' | /usr/bin/base64 -d -i 2> /dev/null
	fi
}

get_server_index(){
	[ -f "/etc/config/shadowsocks" ] && {
        ssindex=$(uci show shadowsocks | grep -c "=servers")
	}	
}

get_local_servers(){
	[ -f "/etc/config/shadowsocks" ] && [ "`uci show shadowsocks|grep -c "online\["`" -gt 0 ] && {
		get_server_index
		for i in `seq $ssindex -1 1`
		do
			[ "$(uci show shadowsocks.@servers[$(($i-1))]|grep -c "online\[")" -eq 1 ] && {
				if [ ! -f "/usr/share/shadowsocks/serverconfig/all_localservers" ]; then
					echo $(config_t_get servers server $(($i-1))) > /usr/share/shadowsocks/serverconfig/all_localservers
				else
					echo $(config_t_get servers server $(($i-1))) >> /usr/share/shadowsocks/serverconfig/all_localservers
				fi
			}
		done
	}
}

add_servers(){

	get_server_index
	uci add shadowsocks servers >/dev/null
	config_t_set servers remarks $ssindex online[$ssindex]-${remarks}
	config_t_set servers server $ssindex $server
	config_t_set servers server_port $ssindex $server_port
	config_t_set servers protocol $ssindex $protocol
	config_t_set servers encrypt_method $ssindex $encrypt_method
	config_t_set servers obfs $ssindex $obfs
	config_t_set servers password $ssindex $password
	config_t_set servers obfs_param $ssindex $obfsparam
	config_t_set servers timeout $ssindex 300
	config_t_set servers local_port $ssindex 1080
	config_t_set servers fast_open $ssindex false
	config_t_set servers server_type $ssindex ssr
	uci commit shadowsocks
}

get_remote_config(){
	decode_link=$1
	server=$(echo "$decode_link" |awk -F':' '{print $1}')
	server_port=$(echo "$decode_link" |awk -F':' '{print $2}')
	protocol=$(echo "$decode_link" |awk -F':' '{print $3}')
	encrypt_method=$(echo "$decode_link" |awk -F':' '{print $4}')
	obfs=$(echo "$decode_link" |awk -F':' '{print $5}')
	password=$(decode_url_link $(echo "$decode_link" |awk -F':' '{print $6}'|awk -F'/' '{print $1}') 0)
	
	obfsparm_temp=$(echo "$decode_link" |awk -F':' '{print $6}'|awk -F'&' '{print $1}'|awk -F'=' '{print $2}')
	if [ -n "$obfsparm_temp" ]; then
		obfsparam=$(decode_url_link $obfsparm_temp 0)
	else
		obfsparam=''
	fi
	if [ "$(echo "$decode_link" | grep -c protoparam)" -eq 1 ]; then
		#protoparam_temp=$(echo "$decode_link" |awk -F':' '{print $6}'|awk -F'&' '{print $2}'|awk -F'=' '{print $2}')
		#protoparam=$(decode_url_link $protoparam_temp 0)
		remarks_temp=$(echo "$decode_link" |awk -F':' '{print $6}'|awk -F'&' '{print $3}'|awk -F'=' '{print $2}')
		remarks=$(decode_url_link $remarks_temp 0)
	else	
		remarks_temp=$(echo "$decode_link" |awk -F':' '{print $6}'|awk -F'&' '{print $2}'|awk -F'=' '{print $2}')
		remarks=$(decode_url_link $remarks_temp 0)
	fi
	
	##把全部服务器节点写入文件 /usr/share/shadowsocks/serverconfig/all_onlineservers
	if [ ! -f "/usr/share/shadowsocks/serverconfig/all_onlineservers" ]; then
		echo $server > /usr/share/shadowsocks/serverconfig/all_onlineservers
	else
		echo $server >> /usr/share/shadowsocks/serverconfig/all_onlineservers
	fi
	
}

update_config(){

	isadded_server=$(uci show shadowsocks | grep -c "server=\'$server\'")
	if [ "$isadded_server" -eq 0 ]; then
		add_servers
		let addnum+=1

	else
		index=$(uci show shadowsocks|grep -w "server=\'$server\'" | cut -d '[' -f2|cut -d ']' -f1)
		local_server_port=$(config_t_get servers server_port $index)
		local_protocol=$(config_t_get servers protocol $index)
		local_encrypt_method=$(config_t_get servers encrypt_method $index)
		local_obfs=$(config_t_get servers obfs $index)
		local_password=$(config_t_get servers password $index)
		local_remarks=$(echo "$(config_t_get servers remarks $index)" | awk -F'-' '{print $2}')
		local i=0
		[ "$(uci show shadowsocks.@servers[$index] | grep -c "obfs_param")" -eq 1 ] && {
			local_obfsparam=$(config_t_get servers obfs_param $index)
			[ "$local_obfsparam" != "$obfsparam" ] && config_t_set servers obfs_param $index $obfsparam
			let i+=1
		}
		[ "$local_server_port" != "$server_port" ] && config_t_set servers server_port $index $server_port && let i+=1
		[ "$local_protocol" != "$protocol" ] && config_t_set servers protocol $index $protocol && let i+=1
		[ "$local_encrypt_method" != "$encrypt_method" ] && config_t_set servers encrypt_method $index $encrypt_method && let i+=1
		[ "$local_obfs" != "$obfs" ] && config_t_set servers obfs $index $obfs && let i+=1
		[ "$local_password" != "$password" ] && config_t_set servers password $index $password && let i+=1
		[ "$local_remarks" != "$remarks" ] && config_t_set servers remarks $index online[$index]-$remarks
		[ "$i" -gt 0 ] && uci commit shadowsocks && let updatenum+=1
	fi

}

del_config(){
	##删除订阅服务器已经不存在的节点
	for localserver in $(cat /usr/share/shadowsocks/serverconfig/all_localservers)
	do
		[ "`cat /usr/share/shadowsocks/serverconfig/all_onlineservers |grep -c "$localserver"`" -eq 0 ] && {
			for localindex in $(uci show shadowsocks|grep -w "$localserver" |grep -w "server=" |cut -d '[' -f2|cut -d ']' -f1)
			do
				uci delete shadowsocks.@servers[$localindex]
				uci commit shadowsocks
				let delnum+=1 #删除该节点
			done
		}
	done
}

del_all_config(){
	get_server_index
	[ "`uci show shadowsocks|grep -c "online\["`" -eq 0 ] && exit 0
	for i in `seq $ssindex -1 1`
	do
		[ "$(uci show shadowsocks.@servers[$(($i-1))]|grep -c "online\[")" -eq 1 ] && uci delete shadowsocks.@servers[$(($i-1))] && uci commit shadowsocks
	done
	current_global_server=$(config_t_get global global_server)
	[ "$current_global_server" != "nil" ] && config_t_set global global_server 0 'nil' && \
		uci commit shadowsocks && /etc/init.d/shadowsocks stop
}

set_firstserver(){

	serverindex=$(uci show shadowsocks|grep "online\[" | head -1 | awk -F'.' '{print $2}')
	[ -n "$serverindex" ] && new_global_server=$(uci show shadowsocks.$serverindex.server | awk -F'.' '{print $2}') || exit 0
	config_t_set global global_server 0 $new_global_server
	uci commit shadowsocks
	echo "$(date): 原服务器已被删除，更换使用新的服务器地址：$(uci get shadowsocks.$serverindex.server)" >> $LOG_FILE
	/etc/init.d/shadowsocks restart
}

update_global_server(){
	current_global_server=$(config_t_get global global_server)
	if [ "$current_global_server" != "nil" ]; then
		[ -f "/var/etc/shadowsocks.json" ] && current_server=$(cat /var/etc/shadowsocks.json| grep "server\""| awk -F'"' '{print $4}') || exit 0
		tempindex=$(uci show shadowsocks|grep "$current_server" | awk -F'.' '{print $2}')
		if [ -n "$tempindex" ]; then
			for tindex in $tempindex
			do
				[ -n "$(uci get shadowsocks.$tindex.remarks| grep "online\[")" ] && \
					[ "$(cat /usr/share/shadowsocks/serverconfig/all_onlineservers |grep -c "$current_server")" -eq 0 ] && \
						set_firstserver
			done
		else
			set_firstserver
		fi
	fi
}

LOG_FILE=/var/log/$CONFIG.log

start() {
	local addnum=0
	local updatenum=0
	local delnum=0
	echo "$(date): =============================================================================================" >> $LOG_FILE
	echo "$(date):                                                               服务器订阅程序(Shell by stones)" >> $LOG_FILE
	echo "$(date): =============================================================================================" >> $LOG_FILE
	echo "$(date): 开始更新在线订阅列表..." >> $LOG_FILE
	baseurl=$(uci get shadowsocks.@global[0].baseurl)  ##订阅地址
	[ -z "$baseurl" ] && echo "$(date): 请先输入订阅地址保存提交之后再更新！" >> $LOG_FILE && exit 0
	
	#防止并发开启服务
	[ -f "$LOCK_FILE" ] && return 3
	touch "$LOCK_FILE"

	[ ! -d "/usr/share/shadowsocks/onlineurl" ] && mkdir -p /usr/share/shadowsocks/onlineurl
	[ ! -d "/usr/share/shadowsocks/serverconfig" ] && mkdir -p /usr/share/shadowsocks/serverconfig
	rm -f /usr/share/shadowsocks/onlineurl/*
	wget $baseurl -P /usr/share/shadowsocks/onlineurl
	[ ! -d "/usr/share/shadowsocks/onlineurl" ] || [ "$(ls /usr/share/shadowsocks/onlineurl |wc -l)" -eq 0 ] && echo "$(date): 订阅链接下载失败，请重试！" >> $LOG_FILE && rm -f "$LOCK_FILE" && exit 0
	rm -f /usr/share/shadowsocks/serverconfig/*
	get_local_servers
	for file in /usr/share/shadowsocks/onlineurl/*
	do
		[ -z "$(du -sh $file 2> /dev/null)" ] && echo "$(date): 订阅链接下载 $file 失败，请重试！" >> $LOG_FILE && continue
		maxnum=$(cat "$file" | /usr/bin/base64 -d 2> /dev/null| grep "MAX=" |awk -F"=" '{print $2}')
		if [ -n "$maxnum" ]; then
			urllinks=$(cat "$file" | /usr/bin/base64 -d 2> /dev/null| sed '/MAX=/d' | shuf -n${maxnum} | sed 's/ssr:\/\///g')
		else
			urllinks=$(cat "$file" | /usr/bin/base64 -d 2> /dev/null| sed 's/ssr:\/\///g')
		fi
		[ -z "$urllinks" ] && continue
		for link in $urllinks
		do
			decode_link=$(decode_url_link $link 1)
			get_remote_config $decode_link
			update_config
		done
	done
	[ -f "/usr/share/shadowsocks/serverconfig/all_localservers" ] && del_config
	echo "$(date): 本次更新，新增服务器节点 $addnum 个，修改 $updatenum 个，删除 $delnum 个；现共有节点：$(uci show shadowsocks|grep -c "online\[") 个。" >> $LOG_FILE
	echo "$(date): 在线订阅列表更新完成" >> $LOG_FILE
	update_global_server
	rm -f "$LOCK_FILE"

}

stop() {
	[ "`uci show shadowsocks|grep -c "online\["`" -gt 0 ] && {
		while [ -f "$LOCK_FILE" ]; do
			sleep 1s
		done
		echo "$(date): =============================================================================================" >> $LOG_FILE
		echo "$(date):                                                               服务器订阅程序(Shell by stones)" >> $LOG_FILE
		echo "$(date): =============================================================================================" >> $LOG_FILE
		echo "$(date): 在线订阅节点已全部删除" >> $LOG_FILE
		del_all_config
	}
}