#!/bin/sh /etc/rc.common
#
# Copyright (c) 2016 Arduino Srl
#
# Starts stnfcd
#

START=61
STOP=61

NAME=stnfcd
DAEMON=/usr/bin/$NAME

# Exit gracefully if the package has been removed
[ -x $DAEMON ] || exit 0
[ -c /dev/ttyNFC ] || exit 0

start () {
    echo -n "Starting $NAME: "
    service_start $DAEMON /dev/ttyNFC
    echo "OK"
}

stop () {
    echo -n "Stopping $NAME: "
    service_stop $DAEMON
    echo "OK"
}

reload () {
    service_reload $DAEMON /dev/ttyNFC
}
