obj-$(CONFIG_WCN_USB) += wcn_usb.o
obj-$(CONFIG_WCN_USB) += wcn_usb_rx_tx.o
obj-$(CONFIG_WCN_USB) += wcn_usb_store.o
obj-$(CONFIG_WCN_USB) += wcn_usb_io.o
obj-$(CONFIG_WCN_USB) += wcn_usb_test.o
obj-$(CONFIG_WCN_USB) += wcn_usb_download.o
