#!/bin/sh /etc/rc.common
# Copyright (C) 2015 snqu.com

USE_PROCD=1
START=99

BIN=/usr/sbin/shellinaboxd

start_service() {
	procd_open_instance
	procd_set_param command $BIN -u root -c /usr/share/shellinabox \
		--css=/usr/share/shellinabox/black-on-white.css \
		--css=/usr/share/shellinabox/white-on-black.css \
		--user-css Normal:+/usr/share/shellinabox/black-on-white.css,Reverse:-/usr/share/shellinabox/white-on-black.css
	procd_close_instance
}

