#!/bin/sh

. /lib/ramips.sh
board=$(ramips_board_name)

m1=$(cat /sys/class/net/ra0/address | awk -F':' '{ print $5 }' | awk '{print toupper($0)}')
m2=$(cat /sys/class/net/ra0/address | awk -F':' '{ print $6 }' | awk '{print toupper($0)}')

uci -q batch <<-EOF > /dev/null
	set system.@system[0].hostname=Omega-$m1$m2
    	set system.@led[0].sysfs="$board:amber:system"
    	set system.@led[0].trigger='default-on'
	commit system
	set wireless.@wifi-iface[0].ssid='Omega-$m1$m2'
	set wireless.sta.led='${board}:blue:wifi'
	commit wireless
EOF

exit 0
