#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

# Setting the correct board name in the Linino configuration page which was set to ONE as default

START=99

FILE="/usr/lib/lua/luci/view/linino/config.htm"
BOARD=$(awk '/machine/ {print toupper($4)}' /proc/cpuinfo)

boot () {

    if [ $BOARD != "ONE" ]
    then
        sed -i s/ONE/$BOARD/g $FILE
    fi

}
