#!/bin/sh /etc/rc.common
#Init script for udevd

START=30

start() {
	# create /var/run folder
	[ ! -d /var/run ] && mkdir -p /var/run
    #----------- START the UDEV daemon --------------
    /sbin/udevd --daemon &
    }

stop() {
    killall udevd
}
