#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.shadowsocks
	set firewall.shadowsocks=include
	set firewall.shadowsocks.type=script
	set firewall.shadowsocks.path=/usr/share/shadowsocks/firewall.include
	set firewall.shadowsocks.family=any
	set firewall.shadowsocks.reload=1
	commit firewall
EOF
exit 0