#!/bin/sh /etc/rc.common
# Copyright (C) 2015 Nordic Semiconductor

#start after bluetoothd (62)
START=63
PROG=/usr/bin/bluetooth_6lowpand
HCICONFIG=/usr/bin/hciconfig

start() {
	echo "start bluetooth_6lowpand"
	sleep 1
	echo 35 > /sys/kernel/debug/bluetooth/6lowpan_psm
	sleep 1
	killall bluetoothd
	sleep 1
	$HCICONFIG hci0 reset
	$PROG -w 3 -t 5 -W -d
}

stop() {
	echo "stop bluetooth_6lowpand"
	killall -9 bluetooth_6lowpand
}
